file=open('Codingal.txt','r')
print(file.read())
file.close()
file=open('Codingal.txt','r')
print("\n Reading first 8 characters of the file \n")
print(file.read(8))
file.close()
file=open('Codingal.txt','a')
file.write("\n This is an appended text.")
file.close()