file_read=open('Codingal.txt','r')
print("File in Read Mode -")
print(file_read.read())
file_read.close()
file_write=open('Codingal.txt','w')
file_write.write("File in write mode ....")
file_write.write("\n This in write mode and a new text")
file_append=open('Codingal.txt','a')
file_append.write("\n This is an append mode and appended text")
file_append.close()